### ISSUE TITLE
App don't start on linux Manjaro i3-gaps (Arch)

### ISSUE THREAD

**Issue by facku** [GeekyAnts/express-typescript#3]
**Describe the bug**
I cant start the app on Manjaro I3.

I clone the repo, then install node packages with yarn and finally i
```
sudo yarn dev 
sudo npm run dev
```

and i get this error:

```
[15:57:43] Starting compilation in watch mode...

src/providers/Express.ts:63:29 - error TS2769: No overload matches this call.
  The last overload gave the following error.
    Argument of type '(_error: any) => void' is not assignable to parameter of type '() => void'.

63  	this.express.listen(port, (_error: any) => {
    	                          ~~~~~~~~~~~~~~~~~~

  node_modules/@types/express-serve-static-core/index.d.ts:1036:5
    1036     listen(handle: any, listeningListener?: () => void): http.Server;
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    The last overload is declared here.

[15:57:47] Found 1 error. Watching for file changes.
```

**Comment by facku** [comment]
Sorry for my english

**Comment by faizahmedfarooqui** [comment]
Can you try using **npm** instead of **yarn** to install the npm dependencies? And re-run the app again — If this does not work out then you can try the below mentioned suggestion in your local setup.

**_Try changing code in [Express.ts provider's line 63](https://github.com/GeekyAnts/express-typescript/blob/master/src/providers/Express.ts#L63)_**

- **_from:_** ```this.express.listen(port, (_error: any) => {```
- **_to     :_** ```this.express.listen(port, (_error?: any) => {```
